org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1, 26.1.1, 26.1.2,]
neo_version=26.1.2.30-beta
neo_version_range=[26.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=fun_tnt
mod_name=Fun TNT
mod_license=All Rights Reserved
mod_version=2.7
mod_group_id=nicusha.fun_tnt
mod_authors=Nicusha
mod_description=Adds new tnt types.
mod_url=https://legacy.curseforge.com/minecraft/mc-mods/fun-tnt
mod_logo=logo.png
issue_tracker_url="https://github.com/NicosaurusRex99/FunTNT/issues"
mod_update_json=https://raw.githubusercontent.com/NicosaurusRex99/Nicusha-mod-assets/refs/heads/main/fun_tnt_update.json

## Dependencies
jei_version=29.5.0.24

configured_id=7820636